namespace SpriteKind {
    export const item = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    game.over(false)
})
info.onCountdownEnd(function () {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.doorOpenNorth, function (sprite, location) {
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.buttonOrange)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleInsignia, function (sprite, location) {
    info.startCountdown(20)
    scene.cameraShake(4, 5000)
})
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level3`)
game.showLongText("the objective of the game is too...", DialogLayout.Full)
game.showLongText("stand on the pressure plate at the end of the maze", DialogLayout.Full)
game.showLongText("Once the pressure plate has been triggered...", DialogLayout.Full)
game.showLongText(" you will have 15 seconds to find the hidden door behind the fake wall that leads to the hidden chest", DialogLayout.Full)
game.showLongText("touch the hidden chest to WIN!! Use arrow keys or joystick to move", DialogLayout.Full)
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ..........1111..........
    .........111111.........
    ........11111111........
    ........11111111........
    ........dd1111dd........
    ........dbfddfbd........
    ........dcf11fcd........
    .........111111.........
    .........cdb1bd.........
    .......11cb.b.c11.......
    .......1b1....1b1.......
    .......b........b.......
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
scene.cameraFollowSprite(mySprite)
mySprite.setPosition(10, 30)
